### ISSUE TITLE
Not working on vscode 1.78.2 (windows 10)

### ISSUE THREAD

**Issue by elich11** [maxim-saplin/cptX#1]
command not found.

**Comment by maxim-saplin** [comment]
Did you try updating with extenison? Please check what version do you have. Also check that you have all settings in place, recrlently there was support for Azure added, it might be that settings need to be fixed

**Comment by elich11** [comment]
I'm fully UpToDate.
All setting (api key) are in place.
Please check on your side.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxim-saplin** [comment]
The error popup, is there any detail shown when you click expand arrow?

**Comment by elich11** [comment]
Sorry, no detail

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxim-saplin** [comment]
Won't be able to check for another few hours. In the meantime you can try uninstallomg the extension, reloadong VSCode and installing it again

**Comment by maxim-saplin** [comment]
Tried on my Windows 11 VM, indeed right after update had same issue. Uninstalled extension, closed VSCode, opened VSCode and installed extension once again, typed command and picked one - started working. My suspect is that there could be a command cached which was no longer available from updated extension

**Comment by elich11** [comment]
Works!

Thanks,
Eli



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
